server:
  port: 80
  servlet:
    context-path: /gph
spring:
  application:
    name: zfb-server
  data:
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gph?Unicode=true$characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  mvc:
    static-path-pattern: /**
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full
  type-aliases-package: cn.bdqn.gph.entity
  mapper-locations: classpath:mapper/*.xml

